### ISSUE TITLE
1.0.1 Crashes due to missing license field in mods.toml

### ISSUE THREAD

**Issue by jenewland1999** [LotuxPunk/OpenBackup#10]
You need to add the license field to the `mods.toml` file in order to prevent crashes in 1.16.2. 😃 See the example one in Forge repo for more info.

**Comment by LotuxPunk** [comment]
Hi ! Which version are you using ?

**Comment by LotuxPunk** [comment]
Apparently there was a problem during compilation, because I had indicated the license, but it is indeed not present. I just reuploaded the file.

Thanks for reporting it !

**Comment by jenewland1999** [comment]
Apologies for not including the version. I was a bit occupied at the time but wanted to make sure you got the report asap 😃
