### ISSUE TITLE
Video of what happens when I use the OpenBackup Mod

### ISSUE THREAD

**Issue by jillv46** [LotuxPunk/OpenBackup#11]
https://www.dropbox.com/s/ucz5s5fk1oogaj4/2020-08-30%2023-42-41.flv?dl=0

**Comment by LotuxPunk** [comment]
Cannot fix that, it's due to Minecraft saving stuff

**Comment by PaintNinja** [comment]
Triggerring a world save when running the backup command but before running the actual backup could fix this however @LotuxPunk .

A workaround @jillv46 is to pause the game and wait a few seconds before resuming the game and running the backup command.

**Comment by LotuxPunk** [comment]
@PaintNinja FYI you don't have access to save stuff on single player, that only a feature on dedicated server.
