### ISSUE TITLE
Possibly to Actually Disable Messages?

### ISSUE THREAD

**Issue by FriendlyGamer** [LotuxPunk/OpenBackup#3]
I tried deleting the messages from the config so that nothing remains after the "=" sign but it just output blank lines instead of actually nothing. Could you please consider implementing a way to turn this off?  

Because I believe it's a security risk if people know when the server is being backed up as simply as viewing the chats. For instance to plan a detailed griefing attempt. Which may be harder to recover from.  

Please let me know if there is indeed already a way to do that? Thanks!

**Comment by LotuxPunk** [comment]
Hello! Thanks for the feedback. I'll add a way to enable the message for All, Op or none. That's a great suggestion, thanks!

**Comment by LotuxPunk** [comment]
Suggestion added in this update: https://minecraft.curseforge.com/projects/openbackup/files/2675513 👍
